version: '2'

services:
  orderer:
    container_name: orderer
    image: hyperledger/fabric-orderer:latest
    environment:
      - ORDERER_GENERAL_LOGLEVEL=debug
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererOrg
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/tls/ca.crt]
    working_dir: /etc/hyperledger
    command: orderer
    volumes:
      - ./configtx.yaml:/etc/hyperledger/configtx/configtx.yaml
      - ./crypto-config/ordererOrganizations/ordererorg:/etc/hyperledger/msp/orderer
      - ./crypto-config/peerOrganizations/org1:/etc/hyperledger/msp/peer
      - ./crypto-config:/etc/hyperledger/tls
    ports:
      - "7050:7050"

  peer0.org1:
    container_name: peer0.org1
    image: hyperledger/fabric-peer:latest
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.org1
      - CORE_PEER_ADDRESS=peer0.org1:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.org1:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0: 7052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.org1:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.org1:7051
      - CORE_PEER_LOCALMSPID=Org1
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/tls/ca.crt
    working_dir: /etc/hyperledger
    command: peer node start
    volumes:
      - ./configtx.yaml:/etc/hyperledger/configtx/configtx.yaml
      - ./crypto-config/peerOrganizations/org1:/etc/hyperledger/msp/peer
      - ./crypto-config:/etc/hyperledger/tls
    ports:
      - "7051:7051"
    depends_on:
      - orderer